### ISSUE TITLE
A bug fix in Django 2.0.6 has broken django-js-reverse

### ISSUE THREAD

**Issue by BITSOLVER** [ierror/django-js-reverse#65]
I believe the following Django issue fix to be the cause of the problem:

https://code.djangoproject.com/ticket/29415

Here's a stack trace from django-admin collectstatic_js_reverse

`Traceback (most recent call last):
  File "/Users/steven/dev/VIRTUALENVS-3.6/BookingsManager/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/Users/steven/dev/VIRTUALENVS-3.6/BookingsManager/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/steven/dev/VIRTUALENVS-3.6/BookingsManager/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/steven/dev/VIRTUALENVS-3.6/BookingsManager/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/steven/dev/VIRTUALENVS-3.6/BookingsManager/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/steven/dev/VIRTUALENVS-3.6/BookingsManager/lib/python3.6/site-packages/django_js_reverse/management/commands/collectstatic_js_reverse.py", line 41, in handle
    content = generate_js(default_urlresolver)
  File "/Users/steven/dev/VIRTUALENVS-3.6/BookingsManager/lib/python3.6/site-packages/django_js_reverse/core.py", line 120, in generate_js
    'urls': sorted(list(prepare_url_list(default_urlresolver))),
  File "/Users/steven/dev/VIRTUALENVS-3.6/BookingsManager/lib/python3.6/site-packages/django_js_reverse/core.py", line 87, in prepare_url_list
    inner_urlresolver)
TypeError: get_ns_resolver() missing 1 required positional argument: 'converters'`

**Comment by kavdev** [comment]
Just ran into the same issue. Here's the [diff](https://github.com/django/django/pull/9965/files).

I haven't had a chance to dig into the new [custom path converter](https://docs.djangoproject.com/en/2.0/topics/http/urls/#registering-custom-path-converters) features to fully understand how it all works, but I think simply using ``tuple(inner_urlresolver.pattern.converters.items())`` as the converters argument [here](https://github.com/ierror/django-js-reverse/blob/develop/django_js_reverse/core.py#L86) might work.

Thoughts?

**Comment by kavdev** [comment]
Unless anyone has any objections to the solution proposed above (e.g. "nooooo, that'll break my custom path stuff!"), I'm going to submit it as a PR

**Comment by kavdev** [comment]
@ierror PR is up: https://github.com/ierror/django-js-reverse/pull/66

**Comment by ierror** [comment]
Thank you, Just released v0.8.2

**Comment by BITSOLVER** [comment]
Thank you for releasing a fix
