### ISSUE TITLE
NameError: name 'django_js_reverse' is not defined

### ISSUE THREAD

**Issue by adder46** [ierror/django-js-reverse#92]
I installed the package with pip and added `'django_js_reverse'` in my `INSTALLED_APPS`, however I'm getting an error:

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alex/.repos/codelib/practice/coinshop/src/coinshop/coinshop/urls.py", line 28, in <module>
    path('shop/', include('products.urls'))
  File "/home/alex/.repos/codelib/practice/coinshop/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alex/.repos/codelib/practice/coinshop/src/coinshop/products/urls.py", line 12, in <module>
    path('jsreverse/', django_js_reverse.views.urls_js, name='js_reverse'),
NameError: name 'django_js_reverse' is not defined
```
Here is my `urls.py` line:

`path('jsreverse/', django_js_reverse.views.urls_js, name='js_reverse'),`

I'm using Python 3.6.8 and Django 2.2.5.

**Comment by adder46** [comment]
When I import it, I get `AttributeError: module 'django_js_reverse' has no attribute 'views'`.
